library(tidyverse)
library(dplyr)
library(gtsummary)
library(ggplot2)
library(gt)
library(readxl)
library(data.table)
library(ggrepel)
library(knitr)
library(yaml)
library(rmarkdown)
library(here)

here::i_am("Code/04_Render_Report.R")

render("report.Rmd",knit_root_dir = here::here())